# Site settings
author: Anthony Prescott-Brooks
title: Anthony's Blog
header-img: img/home-bg.png
email: anthonybrooks226@gmail.com
copyright_name: Anthony Prescott-Brooks
description: > # this means to ignore newlines until "baseurl:"
  my adventures in programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  anthonbrooks

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
